using ConnectorLib.SimpleTCP;
using CrowdControl.Common;
using ConnectorType = CrowdControl.Common.ConnectorType;

namespace CrowdControl.Games.Packs.TCGCardShopSimulator;

public class TCGCardShopSimulator : SimpleTCPPack<SimpleTCPServerConnector>
{
    public override string Host => "127.0.0.1";

    public override ushort Port => 51337;

    public override ISimpleTCPPack.MessageFormat MessageFormat => ISimpleTCPPack.MessageFormat.CrowdControlLegacy;

    public TCGCardShopSimulator(UserRecord player, Func<CrowdControlBlock, bool> responseHandler, Action<object> statusUpdateHandler) : base(player, responseHandler, statusUpdateHandler) { }

    public override Game Game { get; } = new("TCG Card Shop Simulator", "TCGCardShopSimulator", "PC", ConnectorType.SimpleTCPServerConnector);

    public override EffectList Effects { get; } = new List<Effect>
    {
        new("Toggle Lights", "lights") { Description = "Toggle the Shop Lights", Category = "Misc", Price = 15 },
        new("Open Store", "open_store") { Description = "Opens the Players Store", Category = "Misc", Price = 100 },
        new("Close Store", "close_store") { Description = "Closes the Players Store", Category = "Misc", Price = 100 },
        new("Make the Player Rename the Store", "renamestore") { Description = "Forces the Player to rename their store!", Category = "Misc", Price = 100 },
        new("Unlock Storage", "unlockwh") { Description = "Unlock The Storage room", Category = "Misc", Price = 250 },
        new("Upgrade Storage", "upgradewh") { Description = "Upgrade the Storage Room", Category = "Misc", Price = 1000 },
        new("Make All Customers Stinky", "allsmelly") { Description = "Make All the Customers Smelly", Category = "Misc", Price = 150 },
        new("Upgrade the Player Store", "upgradestore") { Description = "Upgrades the Player Store Size", Category = "Misc", Price = 2000 },

        new("Spawn Customer", "spawn") { Description = "Spawns a New Customer", Category = "Spawn", Price = 100 },
        new("Spawn Stinky Customer", "spawnsmelly") { Description = "Spawns a New Extra Stinky Customer", Category = "Spawn", Price = 125 },

        new("Teleport Player Away", "teleport") { Description = "Teleports the Player out of the Store Randomly", Category = "Player", Price = 50 },
        new("Throw Player Item", "throwitem") { Description = "Make the player throw their item!", Category = "Player", Price = 25 },

        new("Give $100", "give_100") { Description = "Give the Player $100", Category = "Money", Price = 10 },
        new("Give $1000", "give_1000") { Description = "Give the Player $1000", Category = "Money", Price = 100 },
        new("Give $10000", "give_10000") { Description = "Give The Player $10000", Category = "Money", Price = 500 },
        new("Take $100", "take_100") { Description = "Take away $100 from the Player", Category = "Money", Price = 15 },
        new("Take $1000", "take_1000") { Description = "Take Away $1000 from the Player", Category = "Money", Price = 150 },
        new("Take $10000", "take_10000") { Description = "Take Away $10000 from the Player", Category = "Money", Price = 700 },

        new("Force Cash Only", "forcepayment_cash") { Description = "Force all customers to pay with cash only.", Duration = 60, Category = "Payments", Price = 25 },
        new("Force Card Only", "forcepayment_card") { Description = "Force all customers to pay with card only.", Duration = 60, Category = "Payments", Price = 25 },
        new("Force Large Bills", "largebills") { Description = "Force customers that are paying with cash to use \"Large Bills\".", Duration = 60, Category = "Payments", Price = 50 },
        new("Force Exact Change", "exactchange") { Description = "Customers pay with Exact amounts when using Cash!", Duration = 60, Category = "Payments", Price = 100 },
        new("Make the streamer do the Math", "forcemath") { Description = "Force The Player to do Math", Duration = 30, Category = "Payments", Price = 100 },

        new("Give Empty Box", "giveempty") { Description = "Send the player an Empty Box!", Category = "Items", Image = "box", Price = 100 },
        //new("Give 32 Common Packs", "give_common_pack_(32)") { Description = "Send the player a Common Pack (32)", Category = "Items", Image = "box", Price = 100 },
        new("Give 64 Common Packs", "give_common_pack_(64)") { Description = "Send the player a Common Pack (64)", Category = "Items", Image = "box", Price = 100 },
        //new("Give Common Box (4)", "give_common_box_(4)") { Description = "Send the player a Common Box (4)", Category = "Items", Image = "box", Price = 100 },
        new("Give Common Box (8)", "give_common_box_(8)") { Description = "Send the player a Common Box (8)", Category = "Items", Image = "box", Price = 100 },
        //new("Give Rare Pack (32)", "give_rare_pack_(32)") { Description = "Send the player a Rare Pack (32)", Category = "Items", Image = "box", Price = 100 },
        new("Give Rare Pack (64)", "give_rare_pack_(64)") { Description = "Send the player a Rare Pack (64)", Category = "Items", Image = "box", Price = 100 },
        //new("Give Rare Box (4)", "give_rare_box_(4)") { Description = "Send the player a Rare Box (4)", Category = "Items", Image = "box", Price = 100 },
        new("Give Rare Box (8)", "give_rare_box_(8)") { Description = "Send the player a Rare Box (8)", Category = "Items", Image = "box", Price = 100 },
        //new("Give Epic Pack (32)", "give_epic_pack_(32)") { Description = "Send the player an Epic Pack (32)", Category = "Items", Image = "box", Price = 100 },
        new("Give Epic Pack (64)", "give_epic_pack_(64)") { Description = "Send the player an Epic Pack (64)", Category = "Items", Image = "box", Price = 100 },
        //new("Give Epic Box (4)", "give_epic_box_(4)") { Description = "Send the player an Epic Box (4)", Category = "Items", Image = "box", Price = 100 },
        new("Give Epic Box (8)", "give_epic_box_(8)") { Description = "Send the player an Epic Box (8)", Category = "Items", Image = "box", Price = 100 },
        //new("Give Legend Pack (32)", "give_legend_pack_(32)") { Description = "Send the player a Legend Pack (32)", Category = "Items", Image = "box", Price = 100 },
        new("Give Legend Pack (64)", "give_legend_pack_(64)") { Description = "Send the player a Legend Pack (64)", Category = "Items", Image = "box", Price = 100 },
        //new("Give Legend Box (4)", "give_legend_box_(4)") { Description = "Send the player a Legend Box (4)", Category = "Items", Image = "box", Price = 100 },
        new("Give Legend Box (8)", "give_legend_box_(8)") { Description = "Send the player a Legend Box (8)", Category = "Items", Image = "box", Price = 100 },
        //new("Give Deck Box Red (Small Box)", "give_deck_box_red_(sm)") { Description = "Send the player a Red Deck box (Small)", Category = "Items", Image = "box", Price = 100 },
        new("Give Deck Box Red (Large Box)", "give_deck_box_red") { Description = "Send the player a Red Deck Box (Large)", Category = "Items", Image = "box", Price = 100 },
        //new("Give Deck Box Green (Small Box)", "give_deck_box_green_(sm)") { Description = "Send the player a Green Deck Box (Small)", Category = "Items", Image = "box", Price = 100 },
        new("Give Deck Box Green (Large Box)", "give_deck_box_green") { Description = "Send the player a Green Deck Box (Large)", Category = "Items", Image = "box", Price = 100 },
        //new("Give Deck Box Blue (Small Box)", "give_deck_box_blue_(sm)") { Description = "Send the player a Blue Deck Box (Small)", Category = "Items", Image = "box", Price = 100 },
        new("Give Deck Box Blue (Large Box)", "give_deck_box_blue") { Description = "Send the player a Blue Deck Box (Large)", Category = "Items", Image = "box", Price = 100 },
        //new("Give Deck Box Yellow (Small Box)", "give_deck_box_yellow_(sm)") { Description = "Send the player a Yellow Deck Box (Small)", Category = "Items", Image = "box", Price = 100 },
        new("Give Deck Box Yellow (Large Box)", "give_deck_box_yellow") { Description = "Send the player a Yellow Deck Box (Large)", Category = "Items", Image = "box", Price = 100 },
        //new("Give Destiny Common Pack (32)", "give_destiny_common_pack_(32)") { Description = "Send the player a Destiny Common Pack (32) Box", Category = "Items", Image = "box", Price = 100 },
        new("Give Destiny Common Pack (64)", "give_destiny_common_pack_(64)") { Description = "Send the player a Destiny Common Pack (64) Box", Category = "Items", Image = "box", Price = 100 },
        //new("Give Destiny Common Box (4 Packs)", "give_destiny_common_box_(4)") { Description = "Send the player a Destiny Common Box (4)", Category = "Items", Image = "box", Price = 100 },
        new("Give Destiny Common Box (8 Packs)", "give_destiny_common_box_(8)") { Description = "Send the player a Destiny Common Box (8)", Category = "Items", Image = "box", Price = 100 },
        //new("Give Destiny Rare Pack (32)", "give_destiny_rare_pack_(32)") { Description = "Send the player a Destiny Rare Pack (32) Box", Category = "Items", Image = "box", Price = 100 },
        new("Give Destiny Rare Pack (64)", "give_destiny_rare_pack_(64)") { Description = "Send the player a Destiny Rare Pack (64) Box", Category = "Items", Image = "box", Price = 100 },
        //new("Give Destiny Rare Box (4 Packs)", "give_destiny_rare_box_(4)") { Description = "Send the player a Destiny Rare Box (4)", Category = "Items", Image = "box", Price = 100 },
        new("Give Destiny Rare Box (8)", "give_destiny_rare_box_(8)") { Description = "Send the player a Destiny Rare Box (8)", Category = "Items", Image = "box", Price = 100 },
        //new("Give Destiny Epic Pack (32)", "give_destiny_epic_pack_(32)") { Description = "Send the player a Destiny Epic Pack (32) Box", Category = "Items", Image = "box", Price = 100 },
        new("Give Destiny Epic Pack (64)", "give_destiny_epic_pack_(64)") { Description = "Send the player a Destiny Epic Pack (64) Box", Category = "Items", Image = "box", Price = 100 },
        //new("Give Destiny Epic Box (4 Packs)", "give_destiny_epic_box_(4)") { Description = "Send the player a Destiny Epic Box (4) Packs", Category = "Items", Image = "box", Price = 100 },
        new("Give Destiny Epic Box (8 Packs)", "give_destiny_epic_box_(8)") { Description = "Send the player a Destiny Epic Box (8) Packs", Category = "Items", Image = "box", Price = 100 },
        //new("Give Destiny Legend Pack (32)", "give_destiny_legend_pack_(32)") { Description = "Send the player a Destiny Legend Pack (32) Box", Category = "Items", Image = "box", Price = 100 },
        new("Give Destiny Legend Pack (64)", "give_destiny_legend_pack_(64)") { Description = "Send the player a Destiny Legend Pack (64) Box", Category = "Items", Image = "box", Price = 100 },
        //new("Give Destiny Legend Box (4)", "give_destiny_legend_box_(4)") { Description = "Send the player a Destiny Legend Box (4) Packs", Category = "Items", Image = "box", Price = 100 },
        new("Give Destiny Legend Box (8)", "give_destiny_legend_box_(8)") { Description = "Send the player a Destiny Legend Box (8) Packs", Category = "Items", Image = "box", Price = 100 },
        //new("Give Cleanser (16)", "give_cleanser_(16)") { Description = "Send the player a Cleanser pack of 16", Category = "Items", Image = "box", Price = 100 },
        new("Give Cleanser (32)", "give_cleanser_(32)") { Description = "Send the player a Cleanser pack of 32", Category = "Items", Image = "box", Price = 100 },
        new("Give Collection Book", "give_collection_book") { Description = "Send the player a Collection Book", Category = "Items", Image = "box", Price = 100 },
        new("Give D20 Red Dice", "give_d20_dice_red") { Description = "Send the player D20 Red Dice", Category = "Items", Image = "box", Price = 100 },
        new("Give D20 Blue Dice", "give_d20_dice_blue") { Description = "Send the player D20 Blue Dice", Category = "Items", Image = "box", Price = 100 },
        new("Give D20 Black Dice", "give_d20_dice_black") { Description = "Send the player D20 Black Dice", Category = "Items", Image = "box", Price = 100 },
        new("Give D20 White Dice", "give_d20_dice_white") { Description = "Send the player D20 White Dice", Category = "Items", Image = "box", Price = 100 },
        new("Give Piggy Plushie", "give_piggya_plushie") { Description = "Send the player a Piggy Plushie", Category = "Items", Image = "box", Price = 100 },
        new("Give Golem Plushie", "give_golema_plushie") { Description = "Send the player a Golem Plushie", Category = "Items", Image = "box", Price = 100 },
        new("Give Starfish Plushie", "give_starfisha_plushie") { Description = "Send the player a Starfish Plushie", Category = "Items", Image = "box", Price = 100 },
        new("Give Bat Plushie", "give_bata_plushie") { Description = "Send the player a Bat Plushie", Category = "Items", Image = "box", Price = 100 },
        new("Give Toon Plushie", "give_toonz_plushie") { Description = "Send the player a Toon Plushie", Category = "Items", Image = "box", Price = 100 },
        new("Give Kingstar Plushie", "give_kingstar_plushie") { Description = "Send the player a Kingstar Plushie", Category = "Items", Image = "box", Price = 100 },
        new("Give Bonfiox Plushie", "give_bonfiox_plushie") { Description = "Send the player a Bonfiox Plushie", Category = "Items", Image = "box", Price = 100 },
        new("Give Burpig Figurine", "give_burpig_figurine") { Description = "Send the player a Burpig Figurine", Category = "Items", Image = "box", Price = 100 },
        new("Give Inferhog Figurine", "give_inferhog_figurine") { Description = "Send the player a Inferhog Figurine", Category = "Items", Image = "box", Price = 100 },
        new("Give Blazoar Plushie", "give_blazoar_plushie") { Description = "Send the player a Blazoar Plushie", Category = "Items", Image = "box", Price = 100 },
        new("Give Decimite Figurine", "give_decimite_figurine") { Description = "Send the player a Decimite Figurine", Category = "Items", Image = "box", Price = 100 },
        new("Give Meganite Figurine", "give_meganite_figurine") { Description = "Send the player a Meganite Figurine", Category = "Items", Image = "box", Price = 100 },
        new("Give Giganite Statue", "give_giganite_statue") { Description = "Send the player a Giganite Statue", Category = "Items", Image = "box", Price = 100 },
        new("Give Trickstar Figurine", "give_trickstar_figurine") { Description = "Send the player a Trickstar Figurine", Category = "Items", Image = "box", Price = 100 },
        new("Give Princestar Figurine", "give_princestar_figurine") { Description = "Send the player a Princestar Figurine", Category = "Items", Image = "box", Price = 100 },
        new("Give Lunight Figurine", "give_lunight_figurine") { Description = "Send the player a Lunight Figurine", Category = "Items", Image = "box", Price = 100 },
        new("Give Vampicant Figurine", "give_vampicant_figurine") { Description = "Send the player a Vampicant Figurine", Category = "Items", Image = "box", Price = 100 },
        new("Give Dracunix Figurine", "give_dracunix_figurine") { Description = "Send the player a Dracunix Figurine", Category = "Items", Image = "box", Price = 100 },
        new("Give Drilceros Action Figure", "give_drilceros_action_figure") { Description = "Send the player a Drilceros Action Figure", Category = "Items", Image = "box", Price = 100 },
        new("Give Fire Battle Deck", "give_fire_battle_deck") { Description = "Send the player a Fire Battle Deck", Category = "Items", Image = "box", Price = 100 },
        new("Give Earth Battle Deck", "give_earth_battle_deck") { Description = "Send the player a Earth Battle Deck", Category = "Items", Image = "box", Price = 100 },
        new("Give Water Battle Deck", "give_water_battle_deck") { Description = "Send the player a Water Battle Deck", Category = "Items", Image = "box", Price = 100 },
        new("Give Wind Battle Deck", "give_wind_battle_deck") { Description = "Send the player a Wind Battle Deck", Category = "Items", Image = "box", Price = 100 },
        new("Give Fire Destiny Deck", "give_fire_destiny_deck") { Description = "Send the player a Fire Destiny Deck", Category = "Items", Image = "box", Price = 100 },
        new("Give Earth Destiny Deck", "give_earth_destiny_deck") { Description = "Send the player a Earth Destiny Deck", Category = "Items", Image = "box", Price = 100 },
        new("Give Water Destiny Deck", "give_water_destiny_deck") { Description = "Send the player a Water Destiny Deck", Category = "Items", Image = "box", Price = 100 },
        new("Give Wind Destiny Deck", "give_wind_destiny_deck") { Description = "Send the player a Wind Destiny Deck", Category = "Items", Image = "box", Price = 100 },
        new("Give Clear Card Sleeves", "give_card_sleeves_(clear)") { Description = "Send the player Clear Card Sleeves", Category = "Items", Image = "box", Price = 100 },
        new("Give Tetramon Style Card Sleeves", "give_card_sleeves_(tetramon)") { Description = "Send the player Tetramon Card Sleeves", Category = "Items", Image = "box", Price = 100 },
        new("Give Fire Art Card Sleeves", "give_card_sleeves_(fire)") { Description = "Send the player Fire Art Card Sleeves", Category = "Items", Image = "box", Price = 100 },
        new("Give Earth Art Card Sleeves", "give_card_sleeves_(earth)") { Description = "Send the player Earth Art Card Sleeves", Category = "Items", Image = "box", Price = 100 },
        new("Give Water Art Card Sleeves", "give_card_sleeves_(water)") { Description = "Send the player Water Art Card Sleeves", Category = "Items", Image = "box", Price = 100 },
        new("Give Wind Art Card Sleeves", "give_card_sleeves_(wind)") { Description = "Send the player Wind Art Card Sleeves", Category = "Items", Image = "box", Price = 100 },
        new("Give Playmat (Clamigo)", "give_playmat_(clamigo)") { Description = "Send the player a Clamingo Playmat", Category = "Items", Image = "box", Price = 100 },
        new("Give Playmat (Duel)", "give_playmat_(duel)") { Description = "Send the player a Duel Playmat", Category = "Items", Image = "box", Price = 100 },
        new("Give Playmat (Drilceros)", "give_playmat_(drilceros)") { Description = "Send the player a Drilceros Playmat", Category = "Items", Image = "box", Price = 100 },
        new("Give Playmat (Drakon)", "give_playmat_(drakon)") { Description = "Send the player a Drakon Playmat", Category = "Items", Image = "box", Price = 100 },
        new("Give Playmat (The Four Dragons)", "give_playmat_(the_four_dragons)") { Description = "Send the player a The Four Dragons Playmat", Category = "Items", Image = "box", Price = 100 },
        new("Give Playmat (Dracunix)", "give_playmat_(dracunix)") { Description = "Send the player a Dracunix Playmat", Category = "Items", Image = "box", Price = 100 },
        new("Give Playmat (Wispo)", "give_playmat_(wispo)") { Description = "Send the player a Wispo Playmat", Category = "Items", Image = "box", Price = 100 },
        new("Give Playmat (GigatronX Evo)", "give_playmat_(gigatronx_evo)") { Description = "Send the player a GigatronX Evo Playmat", Category = "Items", Image = "box", Price = 100 },
        new("Give Playmat (Tetramon)", "give_playmat_(tetramon)") { Description = "Send the player a Tetramon Playmat", Category = "Items", Image = "box", Price = 100 },
        new("Give Playmat (Kyrone)", "give_playmat_(kyrone)") { Description = "Send the player a Kyrone Playmat", Category = "Items", Image = "box", Price = 100 },
        new("Give Playmat (Fire)", "give_playmat_(fire)") { Description = "Send the player a Fire Playmat", Category = "Items", Image = "box", Price = 100 },
        new("Give Playmat (Earth)", "give_playmat_(earth)") { Description = "Send the player a Earth Playmat", Category = "Items", Image = "box", Price = 100 },
        new("Give Playmat (Water)", "give_playmat_(water)") { Description = "Send the player a Water Playmat", Category = "Items", Image = "box", Price = 100 },
        new("Give Playmat (Wind)", "give_playmat_(wind)") { Description = "Send the player a Wind Playmat", Category = "Items", Image = "box", Price = 100 },
        new("Give Playmat (Lunight)", "give_playmat_(lunight)") { Description = "Send the player a Lunight Playmat", Category = "Items", Image = "box", Price = 100 },

        //new("Spawn 32 Common Packs on Player", "giveatplayer_common_pack_(32)") { Description = "Send the player a Common Pack (32) at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn a Huge Empty Box to the Player", "giveplayerhugeempty") { Description = "Send the player a HUGE empty Box.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn 64 Common Packs on Player", "giveatplayer_common_pack_(64)") { Description = "Send the player a Common Pack (64) at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        //new("Spawn Common Box (4) on Player", "giveatplayer_common_box_(4)") { Description = "Send the player a Common Box (4) at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn Common Box (8) on Player", "giveatplayer_common_box_(8)") { Description = "Send the player a Common Box (8) at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        //new("Spawn Rare Pack (32) on Player", "giveatplayer_rare_pack_(32)") { Description = "Send the player a Rare Pack (32) at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn Rare Pack (64) on Player", "giveatplayer_rare_pack_(64)") { Description = "Send the player a Rare Pack (64) at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        //new("Spawn Rare Box (4) on Player", "giveatplayer_rare_box_(4)") { Description = "Send the player a Rare Box (4) at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn Rare Box (8) on Player", "giveatplayer_rare_box_(8)") { Description = "Send the player a Rare Box (8) at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        //new("Spawn Epic Pack (32) on Player", "giveatplayer_epic_pack_(32)") { Description = "Send the player an Epic Pack (32) at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn Epic Pack (64) on Player", "giveatplayer_epic_pack_(64)") { Description = "Send the player an Epic Pack (64) at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        //new("Spawn Epic Box (4) on Player", "giveatplayer_epic_box_(4)") { Description = "Send the player an Epic Box (4) at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn Epic Box (8) on Player", "giveatplayer_epic_box_(8)") { Description = "Send the player an Epic Box (8) at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        //new("Spawn Legend Pack (32) on Player", "giveatplayer_legend_pack_(32)") { Description = "Send the player a Legend Pack (32) at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn Legend Pack (64) on Player", "giveatplayer_legend_pack_(64)") { Description = "Send the player a Legend Pack (64) at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        //new("Spawn Legend Box (4) on Player", "giveatplayer_legend_box_(4)") { Description = "Send the player a Legend Box (4) at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn Legend Box (8) on Player", "giveatplayer_legend_box_(8)") { Description = "Send the player a Legend Box (8) at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        //new("Spawn Deck Box Red (Small Box) on Player", "giveatplayer_deck_box_red_(sm)") { Description = "Send the player a Red Deck box (Small) at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn Deck Box Red (Large Box) on Player", "giveatplayer_deck_box_red") { Description = "Send the player a Red Deck Box (Large) at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        //new("Spawn Deck Box Green (Small Box) on Player", "giveatplayer_deck_box_green_(sm)") { Description = "Send the player a Green Deck Box (Small) at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn Deck Box Green (Large Box) on Player", "giveatplayer_deck_box_green") { Description = "Send the player a Green Deck Box (Large) at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        //new("Spawn Deck Box Blue (Small Box) on Player", "giveatplayer_deck_box_blue_(sm)") { Description = "Send the player a Blue Deck Box (Small) at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn Deck Box Blue (Large Box) on Player", "giveatplayer_deck_box_blue") { Description = "Send the player a Blue Deck Box (Large) at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        //new("Spawn Deck Box Yellow (Small Box) on Player", "giveatplayer_deck_box_yellow_(sm)") { Description = "Send the player a Yellow Deck Box (Small) at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn Deck Box Yellow (Large Box) on Player", "giveatplayer_deck_box_yellow") { Description = "Send the player a Yellow Deck Box (Large) at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        //new("Spawn Destiny Common Pack (32) on Player", "giveatplayer_destiny_common_pack_(32)") { Description = "Send the player a Destiny Common Pack (32) Box at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn Destiny Common Pack (64) on Player", "giveatplayer_destiny_common_pack_(64)") { Description = "Send the player a Destiny Common Pack (64) Box at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        //new("Spawn Destiny Common Box (4 Packs) on Player", "giveatplayer_destiny_common_box_(4)") { Description = "Send the player a Destiny Common Box (4) at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn Destiny Common Box (8 Packs) on Player", "giveatplayer_destiny_common_box_(8)") { Description = "Send the player a Destiny Common Box (8) at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        //new("Spawn Destiny Rare Pack (32) on Player", "giveatplayer_destiny_rare_pack_(32)") { Description = "Send the player a Destiny Rare Pack (32) Box at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn Destiny Rare Pack (64) on Player", "giveatplayer_destiny_rare_pack_(64)") { Description = "Send the player a Destiny Rare Pack (64) Box at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        //new("Spawn Destiny Rare Box (4 Packs) on Player", "giveatplayer_destiny_rare_box_(4)") { Description = "Send the player a Destiny Rare Box (4) at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn Destiny Rare Box (8) on Player", "giveatplayer_destiny_rare_box_(8)") { Description = "Send the player a Destiny Rare Box (8) at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        //new("Spawn Destiny Epic Pack (32) on Player", "giveatplayer_destiny_epic_pack_(32)") { Description = "Send the player a Destiny Epic Pack (32) Box at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn Destiny Epic Pack (64) on Player", "giveatplayer_destiny_epic_pack_(64)") { Description = "Send the player a Destiny Epic Pack (64) Box at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        //new("Spawn Destiny Epic Box (4 Packs) on Player", "giveatplayer_destiny_epic_box_(4)") { Description = "Send the player a Destiny Epic Box (4) Packs at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn Destiny Epic Box (8 Packs) on Player", "giveatplayer_destiny_epic_box_(8)") { Description = "Send the player a Destiny Epic Box (8) Packs at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        //new("Spawn Destiny Legend Pack (32) on Player", "giveatplayer_destiny_legend_pack_(32)") { Description = "Send the player a Destiny Legend Pack (32) Box at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn Destiny Legend Pack (64) on Player", "giveatplayer_destiny_legend_pack_(64)") { Description = "Send the player a Destiny Legend Pack (64) Box at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        //new("Spawn Destiny Legend Box (4) on Player", "giveatplayer_destiny_legend_box_(4)") { Description = "Send the player a Destiny Legend Box (4) Packs at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn Destiny Legend Box (8) on Player", "giveatplayer_destiny_legend_box_(8)") { Description = "Send the player a Destiny Legend Box (8) Packs at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        //new("Spawn Cleanser (16) on Player", "giveatplayer_cleanser_(16)") { Description = "Send the player a Cleanser pack of 16 at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn Cleanser (32) on Player", "giveatplayer_cleanser_(32)") { Description = "Send the player a Cleanser pack of 32 at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn Collection Book on Player", "giveatplayer_collection_book") { Description = "Send the player a Collection Book at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn D20 Red Dice on Player", "giveatplayer_d20_dice_red") { Description = "Send the player D20 Red Dice at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn D20 Blue Dice on Player", "giveatplayer_d20_dice_blue") { Description = "Send the player D20 Blue Dice at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn D20 Black Dice on Player", "giveatplayer_d20_dice_black") { Description = "Send the player D20 Black Dice at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn D20 White Dice on Player", "giveatplayer_d20_dice_white") { Description = "Send the player D20 White Dice at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn Piggy Plushie on Player", "giveatplayer_piggya_plushie") { Description = "Send the player a Piggy Plushie at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn Golem Plushie on Player", "giveatplayer_golema_plushie") { Description = "Send the player a Golem Plushie at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn Starfish Plushie on Player", "giveatplayer_starfisha_plushie") { Description = "Send the player a Starfish Plushie at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn Bat Plushie on Player", "giveatplayer_bata_plushie") { Description = "Send the player a Bat Plushie at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn Toon Plushie on Player", "giveatplayer_toonz_plushie") { Description = "Send the player a Toon Plushie at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn Kingstar Plushie on Player", "giveatplayer_kingstar_plushie") { Description = "Send the player a Kingstar Plushie at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn Bonfiox Plushie on Player", "giveatplayer_bonfiox_plushie") { Description = "Send the player a Bonfiox Plushie at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn Burpig Figurine on Player", "giveatplayer_burpig_figurine") { Description = "Send the player a Burpig Figurine at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn Inferhog Figurine on Player", "giveatplayer_inferhog_figurine") { Description = "Send the player a Inferhog Figurine at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn Blazoar Plushie on Player", "giveatplayer_blazoar_plushie") { Description = "Send the player a Blazoar Plushie at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn Decimite Figurine on Player", "giveatplayer_decimite_figurine") { Description = "Send the player a Decimite Figurine at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn Meganite Figurine on Player", "giveatplayer_meganite_figurine") { Description = "Send the player a Meganite Figurine at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn Giganite Statue on Player", "giveatplayer_giganite_statue") { Description = "Send the player a Giganite Statue at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn Trickstar Figurine on Player", "giveatplayer_trickstar_figurine") { Description = "Send the player a Trickstar Figurine at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn Princestar Figurine on Player", "giveatplayer_princestar_figurine") { Description = "Send the player a Princestar Figurine at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn Lunight Figurine on Player", "giveatplayer_lunight_figurine") { Description = "Send the player a Lunight Figurine at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn Vampicant Figurine on Player", "giveatplayer_vampicant_figurine") { Description = "Send the player a Vampicant Figurine at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn Dracunix Figurine on Player", "giveatplayer_dracunix_figurine") { Description = "Send the player a Dracunix Figurine at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn Drilceros Action Figure on Player", "giveatplayer_drilceros_action_figure") { Description = "Send the player a Drilceros Action Figure at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn Fire Battle Deck on Player", "giveatplayer_fire_battle_deck") { Description = "Send the player a Fire Battle Deck at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn Earth Battle Deck on Player", "giveatplayer_earth_battle_deck") { Description = "Send the player a Earth Battle Deck at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn Water Battle Deck on Player", "giveatplayer_water_battle_deck") { Description = "Send the player a Water Battle Deck at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn Wind Battle Deck on Player", "giveatplayer_wind_battle_deck") { Description = "Send the player a Wind Battle Deck at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn Fire Destiny Deck on Player", "giveatplayer_fire_destiny_deck") { Description = "Send the player a Fire Destiny Deck at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn Earth Destiny Deck on Player", "giveatplayer_earth_destiny_deck") { Description = "Send the player a Earth Destiny Deck at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn Water Destiny Deck on Player", "giveatplayer_water_destiny_deck") { Description = "Send the player a Water Destiny Deck at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn Wind Destiny Deck on Player", "giveatplayer_wind_destiny_deck") { Description = "Send the player a Wind Destiny Deck at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn Clear Card Sleeves on Player", "giveatplayer_card_sleeves_(clear)") { Description = "Send the player Clear Card Sleeves at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn Tetramon Style Card Sleeves on Player", "giveatplayer_card_sleeves_(tetramon)") { Description = "Send the player Tetramon Card Sleeves at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn Fire Art Card Sleeves on Player", "giveatplayer_card_sleeves_(fire)") { Description = "Send the player Fire Art Card Sleeves at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn Earth Art Card Sleeves on Player", "giveatplayer_card_sleeves_(earth)") { Description = "Send the player Earth Art Card Sleeves at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn Water Art Card Sleeves on Player", "giveatplayer_card_sleeves_(water)") { Description = "Send the player Water Art Card Sleeves at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn Wind Art Card Sleeves on Player", "giveatplayer_card_sleeves_(wind)") { Description = "Send the player Wind Art Card Sleeves at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn Playmat (Clamigo) on Player", "giveatplayer_playmat_(clamigo)") { Description = "Send the player a Clamingo Playmat at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn Playmat (Duel) on Player", "giveatplayer_playmat_(duel)") { Description = "Send the player a Duel Playmat at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn Playmat (Drilceros) on Player", "giveatplayer_playmat_(drilceros)") { Description = "Send the player a Drilceros Playmat at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn Playmat (Drakon) on Player", "giveatplayer_playmat_(drakon)") { Description = "Send the player a Drakon Playmat at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn Playmat (The Four Dragons) on Player", "giveatplayer_playmat_(the_four_dragons)") { Description = "Send the player a The Four Dragons Playmat at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn Playmat (Dracunix) on Player", "giveatplayer_playmat_(dracunix)") { Description = "Send the player a Dracunix Playmat at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn Playmat (Wispo) on Player", "giveatplayer_playmat_(wispo)") { Description = "Send the player a Wispo Playmat at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn Playmat (GigatronX Evo) on Player", "giveatplayer_playmat_(gigatronx_evo)") { Description = "Send the player a GigatronX Evo Playmat at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn Playmat (Tetramon) on Player", "giveatplayer_playmat_(tetramon)") { Description = "Send the player a Tetramon Playmat at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn Playmat (Kyrone) on Player", "giveatplayer_playmat_(kyrone)") { Description = "Send the player a Kyrone Playmat at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn Playmat (Fire) on Player", "giveatplayer_playmat_(fire)") { Description = "Send the player a Fire Playmat at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn Playmat (Earth) on Player", "giveatplayer_playmat_(earth)") { Description = "Send the player a Earth Playmat at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn Playmat (Water) on Player", "giveatplayer_playmat_(water)") { Description = "Send the player a Water Playmat at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn Playmat (Wind) on Player", "giveatplayer_playmat_(wind)") { Description = "Send the player a Wind Playmat at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Spawn Playmat (Lunight) on Player", "giveatplayer_playmat_(lunight)") { Description = "Send the player a Lunight Playmat at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Send Necromansters Game", "give_necromansters") { Description = "Send the player a Necromansters Board Game", Category = "Items", Image = "box", Price = 250 },
        new("Spawn Necromansters Game on Player", "giveatplayer_necromansters") { Description = "Send the player a Necromansters Board Game at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Send Mafia Works Game", "give_mafia_works") { Description = "Send the Mafia Works Board Game", Category = "Items", Image = "box", Price = 250 },
        new("Spawn Mafia Works Game on Player", "giveatplayer_mafia_works") { Description = "Send the player a Mafia Works Board Game at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Send Claim! Board Game", "give_claim!") { Description = "Send the Claim! Board Game", Category = "Items", Image = "box", Price = 250 },
        new("Spawn Claim! Board game on Player", "giveatplayer_claim!") { Description = "Send the player a Claim! Board Game at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Send System Gate #1 Game", "give_system_gate_#1") { Description = "Send the System Gate #1 Board Game", Category = "Items", Image = "box", Price = 250 },
        new("Spawn System Gate #1 Game on Player", "giveatplayer_system_gate_#1") { Description = "Send the player a System Gate #1 Board Game at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },
        new("Send System Gate #2 Game", "give_system_gate_#2") { Description = "Send the System Gate #2 Board Game", Category = "Items", Image = "box", Price = 250 },
        new("Spawn System Gate #2 Game on Player", "giveatplayer_system_gate_#2") { Description = "Send the player a System Gate #2 Board Game at their feet.", Category = "Player Spawn", Image = "box", Price = 250 },

        new("High FOV", "highfov") { Description = "Set the FOV for the player higher than normal!", Duration = 30, Category = "Game FOV", Price = 100 },
        new("Low FOV", "lowfov") { Description = "Set the FOV for the player lower, giving them tunnel vision!", Duration = 30, Category = "Game FOV", Price = 100 },

        new("Invert X-Axis", "invertx") { Description = "Invert the X-Axis of the players controls!", Duration = 30, Category = "Axis Control", Price = 100 },
        new("Invert Y-Axis", "inverty") { Description = "Invert the Y-Axis of the players controls!", Duration = 30, Category = "Axis Control", Price = 100 },

        new("Set Language to English", "language_english") { Description = "Set Language to English.", Duration = 60, Category = "Game Language", Image = "lang", Price = 50 },//confirmed
        new("Set Language to French", "language_french") { Description = "Set Language to French.", Duration = 60, Category = "Game Language", Image = "lang", Price = 50 },//confirmed
        new("Set Language to German", "language_german") { Description = "Set Language to German.", Duration = 60, Category = "Game Language", Image = "lang", Price = 50 },//confirmed
        new("Set Language to Spanish", "language_spanish") { Description = "Set Language to Spanish.", Duration = 60, Category = "Game Language", Image = "lang", Price = 50 },//confirmed
        new("Set Language to Italian", "language_italian") { Description = "Set Language to Italian.", Duration = 60, Category = "Game Language", Image = "lang", Price = 50 },//confirmed
        new("Set Language to Chinese (Simplified)", "language_chineses") { Description = "Set Language to Chinese (Simplified).", Duration = 60, Category = "Game Language", Image = "lang", Price = 50 },//confirmed
        new("Set Language to Chinese (Traditional)", "language_chineset") { Description = "Set Language to Chinese (Traditional).", Duration = 60, Category = "Game Language", Image = "lang", Price = 50 },//confirmed
        new("Set Language to Korean", "language_korean") { Description = "Set Language to Korean.", Duration = 60, Category = "Game Language", Image = "lang", Price = 50 },//confirmed
        //new("Set Language to Dutch", "language_dutch") { Description = "Set Language to Dutch.", Duration = 60, Category = "Game Language", Image = "lang", Price = 50 },//confirmed

        new("Hey Ohhh", "speak_heyoo") { Description = "Speak!", Category = "Speak", Price = 25 },

        new("Hire new Worker", "hireworker") { Description = "Hire a New Employee!", Category = "Misc", Price = 25 },
        new("Fire Worker", "fireworker") { Description = "Fire a Random Employee", Category = "Misc", Price = 25 },

        new("Send Small Cabinet", "furniture_small_cabinet") { Description = "Send the Player a Small Cabinet!", Category = "Furniture", Price = 250, Image = "table" },
        new("Send Small Metal Rack", "furniture_small_metal_rack") { Description = "Send the player a Small Metal Rack", Category = "Furniture", Price = 250, Image = "table" },
        new("Send Play Table", "furniture_play_table") { Description = "Send the player a Play Table", Category = "Furniture", Price = 250, Image = "table" },
        new("Send Small Personal Shelf", "furniture_small_personal_shelf") { Description = "Send a Personal Shelf", Category = "Furniture", Price = 250, Image = "table" },
        new("Send Single Sided Shelf", "furniture_single_sided_shelf") { Description = "Send a Single Sided Shelf", Category = "Furniture", Price = 250, Image = "table" },
        new("Send Card Table", "furniture_card_table") { Description = "Send a Card Table", Category = "Furniture", Price = 250, Image = "table" },
        new("Send Small Warehouse Shelf", "furniture_small_warehouse_shelf") { Description = "Send a Small Warehouse Shelf", Category = "Furniture", Price = 250, Image = "table" },
        new("Send Small Card Display", "furniture_small_card_display") { Description = "Send a Small Card Display", Category = "Furniture", Price = 250, Image = "table" },
        new("Send Auto Scent M100", "furniture_auto_scent_m100") { Description = "Send an Auto Scent M100", Category = "Furniture", Price = 250, Image = "table" },
        new("Send Workbench", "furniture_workbench") { Description = "Send a Workbench", Category = "Furniture", Price = 250, Image = "table" },
        new("Send Double Sided Shelf", "furniture_double_sided_shelf") { Description = "Send a Double Sided Shelf", Category = "Furniture", Price = 250, Image = "table" },
        new("Send Big Warehouse Shelf", "furniture_big_warehouse_shelf") { Description = "Send a Big Warehouse Shelf", Category = "Furniture", Price = 250, Image = "table" },
        new("Send Checkout Counter", "furniture_checkout_counter") { Description = "Send a Checkout Counter", Category = "Furniture", Price = 250, Image = "table" },
        new("Send Auto Scent G500", "furniture_auto_scent_g500") { Description = "Send an Auto Scent G500", Category = "Furniture", Price = 250, Image = "table" },
        new("Send Card Display Table", "furniture_card_display_table") { Description = "Send a Card Display Table", Category = "Furniture", Price = 250, Image = "table" },
        new("Send Big Personal Shelf", "furniture_big_personal_shelf") { Description = "Send a Big Personal Shelf", Category = "Furniture", Price = 250, Image = "table" },
        new("Send Vintage Card Table", "furniture_vintage_card_table") { Description = "Send a Vintage Card Table", Category = "Furniture", Price = 250, Image = "table" },
        new("Send Wide Shelf", "furniture_wide_shelf") { Description = "Send a Wide Shelf", Category = "Furniture", Price = 250, Image = "table" },
        new("Send Huge Personal Shelf", "furniture_huge_personal_shelf") { Description = "Send a Huge Personal Shelf", Category = "Furniture", Price = 250, Image = "table" },
        new("Send Auto Scent T1000", "furniture_auto_scent_t1000") { Description = "Send Auto Scent t1000", Category = "Furniture", Price = 250, Image = "table" },
        new("Send Big Card Display", "furniture_big_card_display") { Description = "Send Big Card Display", Category = "Furniture", Price = 250, Image = "table" },


        new("Auto Open Common Pack", "openpack_common_pack") { Description = "Automatically spawn in an open a pack, as long as the player is not doing anything else!", Category = "Auto Open", Price = 50, Duration = 8 },
        new("Auto Open Rare Pack", "openpack_rare_pack") { Description = "Automatically spawn in an open a pack, as long as the player is not doing anything else", Category = "Auto Open", Price = 100, Duration = 8 },
        new("Auto Open Epic Pack", "openpack_epic_pack") { Description = "Automatically opens card pack when player is not doinga anything else.", Category = "Auto Open", Price = 150, Duration = 8  },
        new("Auto Open Legend Pack", "openpack_legend_pack") { Description = "Automatically spawn in an open a pack, as long as the player is not doing anything else", Category = "Auto Open", Price = 200, Duration = 8  },
        new("Auto Open Destiny Common Pack", "openpack_destiny_common_pack") { Description = "Automatically spawn in an open a pack, as long as the player is not doing anything else", Category = "Auto Open", Price = 50, Duration = 8  },
        new("Auto Open Destiny Rare Pack", "openpack_destiny_rare_pack") { Description = "Automatically spawn in an open a pack, as long as the player is not doing anything else", Category = "Auto Open", Price = 100, Duration = 8  },
        new("Auto Open Destiny Epic Pack", "openpack_destiny_epic_pack") { Description = "Automatically spawn in an open a pack, as long as the player is not doing anything else", Category = "Auto Open", Price = 150, Duration = 8  },
        new("Auto Open Destiny Legend Pack", "openpack_destiny_legend_pack") { Description = "Automatically spawn in an open a pack, as long as the player is not doing anything else", Category = "Auto Open", Price = 200, Duration = 8  },

        new("Spawn Bread", "spawn_bread") { Description = "Spawn Bread!", Category = "Food", Price = 250 },
        new("Spawn Milk", "spawn_milk") { Description = "Spawn Milk!", Category = "Food", Price = 250 }
    };
}