using System.Text;

namespace CrowdControl.UI;

/// <summary>
/// Display names for effect codes, used by the on-screen overlay.
/// </summary>
/// <remarks>
/// The Crowd Control pack (the .cs file describing your effects to the app) is the single source of
/// truth for what an effect is called. An overlay that disagreed with the menu a viewer just bought
/// from would be worse than no label at all, so fill <see cref="Names"/> in from the pack - a
/// generated block is easiest to keep honest:
///
/// <code>
///     { "speedUp",   "Speed Up" },
///     { "lowGravity", "Low Gravity" },
/// </code>
///
/// Anything missing falls back to a tidied-up version of the code, so the overlay stays readable
/// while an effect is still being written.
/// </remarks>
public static class EffectNames
{
    private static readonly Dictionary<string, string> Names = new(StringComparer.OrdinalIgnoreCase)
    {
        { "lights", "Toggle Lights" },
        { "open_store", "Open Store" },
        { "close_store", "Close Store" },
        { "renamestore", "Make the Player Rename the Store" },
        { "unlockwh", "Unlock Storage" },
        { "upgradewh", "Upgrade Storage" },
        { "allsmelly", "Make All Customers Stinky" },
        { "upgradestore", "Upgrade the Player Store" },
        { "spawn", "Spawn Customer" },
        { "spawnsmelly", "Spawn Stinky Customer" },
        { "teleport", "Teleport Player Away" },
        { "throwitem", "Throw Player Item" },
        { "give_100", "Give $100" },
        { "give_1000", "Give $1000" },
        { "give_10000", "Give $10000" },
        { "take_100", "Take $100" },
        { "take_1000", "Take $1000" },
        { "take_10000", "Take $10000" },
        { "forcepayment_cash", "Force Cash Only" },
        { "forcepayment_card", "Force Card Only" },
        { "largebills", "Force Large Bills" },
        { "exactchange", "Force Exact Change" },
        { "forcemath", "Make the streamer do the Math" },
        { "giveempty", "Give Empty Box" },
        { "give_common_pack_(64)", "Give 64 Common Packs" },
        { "give_common_box_(8)", "Give Common Box (8)" },
        { "give_rare_pack_(64)", "Give Rare Pack (64)" },
        { "give_rare_box_(8)", "Give Rare Box (8)" },
        { "give_epic_pack_(64)", "Give Epic Pack (64)" },
        { "give_epic_box_(8)", "Give Epic Box (8)" },
        { "give_legend_pack_(64)", "Give Legend Pack (64)" },
        { "give_legend_box_(8)", "Give Legend Box (8)" },
        { "give_deck_box_red", "Give Deck Box Red (Large Box)" },
        { "give_deck_box_green", "Give Deck Box Green (Large Box)" },
        { "give_deck_box_blue", "Give Deck Box Blue (Large Box)" },
        { "give_deck_box_yellow", "Give Deck Box Yellow (Large Box)" },
        { "give_destiny_common_pack_(64)", "Give Destiny Common Pack (64)" },
        { "give_destiny_common_box_(8)", "Give Destiny Common Box (8 Packs)" },
        { "give_destiny_rare_pack_(64)", "Give Destiny Rare Pack (64)" },
        { "give_destiny_rare_box_(8)", "Give Destiny Rare Box (8)" },
        { "give_destiny_epic_pack_(64)", "Give Destiny Epic Pack (64)" },
        { "give_destiny_epic_box_(8)", "Give Destiny Epic Box (8 Packs)" },
        { "give_destiny_legend_pack_(64)", "Give Destiny Legend Pack (64)" },
        { "give_destiny_legend_box_(8)", "Give Destiny Legend Box (8)" },
        { "give_cleanser_(32)", "Give Cleanser (32)" },
        { "give_collection_book", "Give Collection Book" },
        { "give_d20_dice_red", "Give D20 Red Dice" },
        { "give_d20_dice_blue", "Give D20 Blue Dice" },
        { "give_d20_dice_black", "Give D20 Black Dice" },
        { "give_d20_dice_white", "Give D20 White Dice" },
        { "give_piggya_plushie", "Give Piggy Plushie" },
        { "give_golema_plushie", "Give Golem Plushie" },
        { "give_starfisha_plushie", "Give Starfish Plushie" },
        { "give_bata_plushie", "Give Bat Plushie" },
        { "give_toonz_plushie", "Give Toon Plushie" },
        { "give_kingstar_plushie", "Give Kingstar Plushie" },
        { "give_bonfiox_plushie", "Give Bonfiox Plushie" },
        { "give_burpig_figurine", "Give Burpig Figurine" },
        { "give_inferhog_figurine", "Give Inferhog Figurine" },
        { "give_blazoar_plushie", "Give Blazoar Plushie" },
        { "give_decimite_figurine", "Give Decimite Figurine" },
        { "give_meganite_figurine", "Give Meganite Figurine" },
        { "give_giganite_statue", "Give Giganite Statue" },
        { "give_trickstar_figurine", "Give Trickstar Figurine" },
        { "give_princestar_figurine", "Give Princestar Figurine" },
        { "give_lunight_figurine", "Give Lunight Figurine" },
        { "give_vampicant_figurine", "Give Vampicant Figurine" },
        { "give_dracunix_figurine", "Give Dracunix Figurine" },
        { "give_drilceros_action_figure", "Give Drilceros Action Figure" },
        { "give_fire_battle_deck", "Give Fire Battle Deck" },
        { "give_earth_battle_deck", "Give Earth Battle Deck" },
        { "give_water_battle_deck", "Give Water Battle Deck" },
        { "give_wind_battle_deck", "Give Wind Battle Deck" },
        { "give_fire_destiny_deck", "Give Fire Destiny Deck" },
        { "give_earth_destiny_deck", "Give Earth Destiny Deck" },
        { "give_water_destiny_deck", "Give Water Destiny Deck" },
        { "give_wind_destiny_deck", "Give Wind Destiny Deck" },
        { "give_card_sleeves_(clear)", "Give Clear Card Sleeves" },
        { "give_card_sleeves_(tetramon)", "Give Tetramon Style Card Sleeves" },
        { "give_card_sleeves_(fire)", "Give Fire Art Card Sleeves" },
        { "give_card_sleeves_(earth)", "Give Earth Art Card Sleeves" },
        { "give_card_sleeves_(water)", "Give Water Art Card Sleeves" },
        { "give_card_sleeves_(wind)", "Give Wind Art Card Sleeves" },
        { "give_playmat_(clamigo)", "Give Playmat (Clamigo)" },
        { "give_playmat_(duel)", "Give Playmat (Duel)" },
        { "give_playmat_(drilceros)", "Give Playmat (Drilceros)" },
        { "give_playmat_(drakon)", "Give Playmat (Drakon)" },
        { "give_playmat_(the_four_dragons)", "Give Playmat (The Four Dragons)" },
        { "give_playmat_(dracunix)", "Give Playmat (Dracunix)" },
        { "give_playmat_(wispo)", "Give Playmat (Wispo)" },
        { "give_playmat_(gigatronx_evo)", "Give Playmat (GigatronX Evo)" },
        { "give_playmat_(tetramon)", "Give Playmat (Tetramon)" },
        { "give_playmat_(kyrone)", "Give Playmat (Kyrone)" },
        { "give_playmat_(fire)", "Give Playmat (Fire)" },
        { "give_playmat_(earth)", "Give Playmat (Earth)" },
        { "give_playmat_(water)", "Give Playmat (Water)" },
        { "give_playmat_(wind)", "Give Playmat (Wind)" },
        { "give_playmat_(lunight)", "Give Playmat (Lunight)" },
        { "give_ascension_pack_(64)", "Give Ascension Pack (64)" },
        { "give_playmat_(gigatronx)", "Give Playmat (GigatronX)" },
        { "give_playmat_(katengu_black)", "Give Playmat (Katengu Black)" },
        { "give_playmat_(katengu_white)", "Give Playmat (Katengu White)" },
        { "give_playmat_gray", "Give Playmat Gray" },
        { "give_playmat_green", "Give Playmat Green" },
        { "give_playmat_purple", "Give Playmat Purple" },
        { "give_playmat_yellow", "Give Playmat Yellow" },
        { "give_magnetic_holder", "Give Magnetic Holder" },
        { "give_card_preserver", "Give Card Preserver" },
        { "give_pocket_pages", "Give Pocket Pages" },
        { "give_card_holder", "Give Card Holder" },
        { "give_toploader", "Give Toploader" },
        { "give_penny_sleeves", "Give Penny Sleeves" },
        { "give_collectors_album", "Give Collectors Album" },
        { "give_tower_deckbox", "Give Tower Deckbox" },
        { "give_evo_blazoar_statue", "Give EVO Blazoar Statue" },
        { "give_evo_kingstar_statue", "Give EVO Kingstar Statue" },
        { "giveplayerhugeempty", "Spawn a Huge Empty Box to the Player" },
        { "giveatplayer_common_pack_(64)", "Spawn 64 Common Packs on Player" },
        { "giveatplayer_common_box_(8)", "Spawn Common Box (8) on Player" },
        { "giveatplayer_rare_pack_(64)", "Spawn Rare Pack (64) on Player" },
        { "giveatplayer_rare_box_(8)", "Spawn Rare Box (8) on Player" },
        { "giveatplayer_epic_pack_(64)", "Spawn Epic Pack (64) on Player" },
        { "giveatplayer_epic_box_(8)", "Spawn Epic Box (8) on Player" },
        { "giveatplayer_legend_pack_(64)", "Spawn Legend Pack (64) on Player" },
        { "giveatplayer_legend_box_(8)", "Spawn Legend Box (8) on Player" },
        { "giveatplayer_deck_box_red", "Spawn Deck Box Red (Large Box) on Player" },
        { "giveatplayer_deck_box_green", "Spawn Deck Box Green (Large Box) on Player" },
        { "giveatplayer_deck_box_blue", "Spawn Deck Box Blue (Large Box) on Player" },
        { "giveatplayer_deck_box_yellow", "Spawn Deck Box Yellow (Large Box) on Player" },
        { "giveatplayer_destiny_common_pack_(64)", "Spawn Destiny Common Pack (64) on Player" },
        { "giveatplayer_destiny_common_box_(8)", "Spawn Destiny Common Box (8 Packs) on Player" },
        { "giveatplayer_destiny_rare_pack_(64)", "Spawn Destiny Rare Pack (64) on Player" },
        { "giveatplayer_destiny_rare_box_(8)", "Spawn Destiny Rare Box (8) on Player" },
        { "giveatplayer_destiny_epic_pack_(64)", "Spawn Destiny Epic Pack (64) on Player" },
        { "giveatplayer_destiny_epic_box_(8)", "Spawn Destiny Epic Box (8 Packs) on Player" },
        { "giveatplayer_destiny_legend_pack_(64)", "Spawn Destiny Legend Pack (64) on Player" },
        { "giveatplayer_destiny_legend_box_(8)", "Spawn Destiny Legend Box (8) on Player" },
        { "giveatplayer_cleanser_(32)", "Spawn Cleanser (32) on Player" },
        { "giveatplayer_collection_book", "Spawn Collection Book on Player" },
        { "giveatplayer_d20_dice_red", "Spawn D20 Red Dice on Player" },
        { "giveatplayer_d20_dice_blue", "Spawn D20 Blue Dice on Player" },
        { "giveatplayer_d20_dice_black", "Spawn D20 Black Dice on Player" },
        { "giveatplayer_d20_dice_white", "Spawn D20 White Dice on Player" },
        { "giveatplayer_piggya_plushie", "Spawn Piggy Plushie on Player" },
        { "giveatplayer_golema_plushie", "Spawn Golem Plushie on Player" },
        { "giveatplayer_starfisha_plushie", "Spawn Starfish Plushie on Player" },
        { "giveatplayer_bata_plushie", "Spawn Bat Plushie on Player" },
        { "giveatplayer_toonz_plushie", "Spawn Toon Plushie on Player" },
        { "giveatplayer_kingstar_plushie", "Spawn Kingstar Plushie on Player" },
        { "giveatplayer_bonfiox_plushie", "Spawn Bonfiox Plushie on Player" },
        { "giveatplayer_burpig_figurine", "Spawn Burpig Figurine on Player" },
        { "giveatplayer_inferhog_figurine", "Spawn Inferhog Figurine on Player" },
        { "giveatplayer_blazoar_plushie", "Spawn Blazoar Plushie on Player" },
        { "giveatplayer_decimite_figurine", "Spawn Decimite Figurine on Player" },
        { "giveatplayer_meganite_figurine", "Spawn Meganite Figurine on Player" },
        { "giveatplayer_giganite_statue", "Spawn Giganite Statue on Player" },
        { "giveatplayer_trickstar_figurine", "Spawn Trickstar Figurine on Player" },
        { "giveatplayer_princestar_figurine", "Spawn Princestar Figurine on Player" },
        { "giveatplayer_lunight_figurine", "Spawn Lunight Figurine on Player" },
        { "giveatplayer_vampicant_figurine", "Spawn Vampicant Figurine on Player" },
        { "giveatplayer_dracunix_figurine", "Spawn Dracunix Figurine on Player" },
        { "giveatplayer_drilceros_action_figure", "Spawn Drilceros Action Figure on Player" },
        { "giveatplayer_fire_battle_deck", "Spawn Fire Battle Deck on Player" },
        { "giveatplayer_earth_battle_deck", "Spawn Earth Battle Deck on Player" },
        { "giveatplayer_water_battle_deck", "Spawn Water Battle Deck on Player" },
        { "giveatplayer_wind_battle_deck", "Spawn Wind Battle Deck on Player" },
        { "giveatplayer_fire_destiny_deck", "Spawn Fire Destiny Deck on Player" },
        { "giveatplayer_earth_destiny_deck", "Spawn Earth Destiny Deck on Player" },
        { "giveatplayer_water_destiny_deck", "Spawn Water Destiny Deck on Player" },
        { "giveatplayer_wind_destiny_deck", "Spawn Wind Destiny Deck on Player" },
        { "giveatplayer_card_sleeves_(clear)", "Spawn Clear Card Sleeves on Player" },
        { "giveatplayer_card_sleeves_(tetramon)", "Spawn Tetramon Style Card Sleeves on Player" },
        { "giveatplayer_card_sleeves_(fire)", "Spawn Fire Art Card Sleeves on Player" },
        { "giveatplayer_card_sleeves_(earth)", "Spawn Earth Art Card Sleeves on Player" },
        { "giveatplayer_card_sleeves_(water)", "Spawn Water Art Card Sleeves on Player" },
        { "giveatplayer_card_sleeves_(wind)", "Spawn Wind Art Card Sleeves on Player" },
        { "giveatplayer_playmat_(clamigo)", "Spawn Playmat (Clamigo) on Player" },
        { "giveatplayer_playmat_(duel)", "Spawn Playmat (Duel) on Player" },
        { "giveatplayer_playmat_(drilceros)", "Spawn Playmat (Drilceros) on Player" },
        { "giveatplayer_playmat_(drakon)", "Spawn Playmat (Drakon) on Player" },
        { "giveatplayer_playmat_(the_four_dragons)", "Spawn Playmat (The Four Dragons) on Player" },
        { "giveatplayer_playmat_(dracunix)", "Spawn Playmat (Dracunix) on Player" },
        { "giveatplayer_playmat_(wispo)", "Spawn Playmat (Wispo) on Player" },
        { "giveatplayer_playmat_(gigatronx_evo)", "Spawn Playmat (GigatronX Evo) on Player" },
        { "giveatplayer_playmat_(tetramon)", "Spawn Playmat (Tetramon) on Player" },
        { "giveatplayer_playmat_(kyrone)", "Spawn Playmat (Kyrone) on Player" },
        { "giveatplayer_playmat_(fire)", "Spawn Playmat (Fire) on Player" },
        { "giveatplayer_playmat_(earth)", "Spawn Playmat (Earth) on Player" },
        { "giveatplayer_playmat_(water)", "Spawn Playmat (Water) on Player" },
        { "giveatplayer_playmat_(wind)", "Spawn Playmat (Wind) on Player" },
        { "giveatplayer_playmat_(lunight)", "Spawn Playmat (Lunight) on Player" },
        { "giveatplayer_ascension_pack_(64)", "Spawn Ascension Pack (64) on Player" },
        { "giveatplayer_playmat_(gigatronx)", "Spawn Playmat (GigatronX) on Player" },
        { "giveatplayer_playmat_(katengu_black)", "Spawn Playmat (Katengu Black) on Player" },
        { "giveatplayer_playmat_(katengu_white)", "Spawn Playmat (Katengu White) on Player" },
        { "giveatplayer_playmat_gray", "Spawn Playmat Gray on Player" },
        { "giveatplayer_playmat_green", "Spawn Playmat Green on Player" },
        { "giveatplayer_playmat_purple", "Spawn Playmat Purple on Player" },
        { "giveatplayer_playmat_yellow", "Spawn Playmat Yellow on Player" },
        { "giveatplayer_magnetic_holder", "Spawn Magnetic Holder on Player" },
        { "giveatplayer_card_preserver", "Spawn Card Preserver on Player" },
        { "giveatplayer_pocket_pages", "Spawn Pocket Pages on Player" },
        { "giveatplayer_card_holder", "Spawn Card Holder on Player" },
        { "giveatplayer_toploader", "Spawn Toploader on Player" },
        { "giveatplayer_penny_sleeves", "Spawn Penny Sleeves on Player" },
        { "giveatplayer_collectors_album", "Spawn Collectors Album on Player" },
        { "giveatplayer_tower_deckbox", "Spawn Tower Deckbox on Player" },
        { "giveatplayer_evo_blazoar_statue", "Spawn EVO Blazoar Statue on Player" },
        { "giveatplayer_evo_kingstar_statue", "Spawn EVO Kingstar Statue on Player" },
        { "give_necromansters", "Send Necromansters Game" },
        { "giveatplayer_necromansters", "Spawn Necromansters Game on Player" },
        { "give_mafia_works", "Send Mafia Works Game" },
        { "giveatplayer_mafia_works", "Spawn Mafia Works Game on Player" },
        { "give_claim!", "Send Claim! Board Game" },
        { "giveatplayer_claim!", "Spawn Claim! Board game on Player" },
        { "give_system_gate_#1", "Send System Gate #1 Game" },
        { "giveatplayer_system_gate_#1", "Spawn System Gate #1 Game on Player" },
        { "give_system_gate_#2", "Send System Gate #2 Game" },
        { "giveatplayer_system_gate_#2", "Spawn System Gate #2 Game on Player" },
        { "highfov", "High FOV" },
        { "lowfov", "Low FOV" },
        { "invertx", "Invert X-Axis" },
        { "inverty", "Invert Y-Axis" },
        { "player_fast", "Super Speed" },
        { "player_slow", "Slow Walk" },
        { "lowgravity", "Moon Gravity" },
        { "slowmo", "Slow Motion" },
        { "fastforward", "Fast Forward" },
        { "hypercustomers", "Hyper Customers" },
        { "mute", "Mute Game Audio" },
        { "badreview", "Leave a Bad Review" },
        { "goodreview", "Leave a Good Review" },
        { "language_english", "Set Language to English" },
        { "language_french", "Set Language to French" },
        { "language_german", "Set Language to German" },
        { "language_spanish", "Set Language to Spanish" },
        { "language_italian", "Set Language to Italian" },
        { "language_chineses", "Set Language to Chinese (Simplified)" },
        { "language_chineset", "Set Language to Chinese (Traditional)" },
        { "language_korean", "Set Language to Korean" },
        { "speak_heyoo", "Hey Ohhh" },
        { "hireworker", "Hire new Worker" },
        { "fireworker", "Fire Worker" },
        { "furniture_small_cabinet", "Send Small Cabinet" },
        { "furniture_small_metal_rack", "Send Small Metal Rack" },
        { "furniture_play_table", "Send Play Table" },
        { "furniture_small_personal_shelf", "Send Small Personal Shelf" },
        { "furniture_single_sided_shelf", "Send Single Sided Shelf" },
        { "furniture_card_table", "Send Card Table" },
        { "furniture_small_warehouse_shelf", "Send Small Warehouse Shelf" },
        { "furniture_small_card_display", "Send Small Card Display" },
        { "furniture_auto_scent_m100", "Send Auto Scent M100" },
        { "furniture_workbench", "Send Workbench" },
        { "furniture_double_sided_shelf", "Send Double Sided Shelf" },
        { "furniture_big_warehouse_shelf", "Send Big Warehouse Shelf" },
        { "furniture_checkout_counter", "Send Checkout Counter" },
        { "furniture_auto_scent_g500", "Send Auto Scent G500" },
        { "furniture_card_display_table", "Send Card Display Table" },
        { "furniture_big_personal_shelf", "Send Big Personal Shelf" },
        { "furniture_vintage_card_table", "Send Vintage Card Table" },
        { "furniture_wide_shelf", "Send Wide Shelf" },
        { "furniture_huge_personal_shelf", "Send Huge Personal Shelf" },
        { "furniture_auto_scent_t1000", "Send Auto Scent T1000" },
        { "furniture_pack_machine_m", "Send Medium Pack Opener" },
        { "furniture_pack_machine_s", "Send Small Pack Opener" },
        { "furniture_pack_machine_l", "Send Large Pack Opener" },
        { "furniture_2x2_cabinet", "Send 2X2 Cabinet" },
        { "furniture_trash_bin", "Send Trash Bin" },
        { "furniture_empty_box_storage", "Send Empty Box Storage" },
        { "furniture_wall_display_case", "Send Wall Display Case" },
        { "furniture_card_projector_s", "Send Card Projector S" },
        { "furniture_card_projector_m", "Send Card Projector M" },
        { "furniture_card_projector_l", "Send Card Projector L" },
        { "furniture_bulk_donation_box", "Send Bulk Donation Box" },
        { "furniture_card_storage_shelf", "Send Card Storage Shelf" },
        { "furniture_tournament_prize_shelf", "Send Tournament Prize Shelf" },
        { "furniture_corner_shelf", "Send Corner Shelf" },
        { "furniture_box_shelf", "Send Box Shelf" },
        { "furniture_tetramon_shelf", "Send Tetramon Shelf" },
        { "furniture_big_card_display", "Send Big Card Display" },
        { "openpack_common_pack", "Auto Open Common Pack" },
        { "openpack_rare_pack", "Auto Open Rare Pack" },
        { "openpack_epic_pack", "Auto Open Epic Pack" },
        { "openpack_legend_pack", "Auto Open Legend Pack" },
        { "openpack_destiny_common_pack", "Auto Open Destiny Common Pack" },
        { "openpack_destiny_rare_pack", "Auto Open Destiny Rare Pack" },
        { "openpack_destiny_epic_pack", "Auto Open Destiny Epic Pack" },
        { "openpack_destiny_legend_pack", "Auto Open Destiny Legend Pack" },
        { "openpack_ascension_pack", "Auto Open Ascension Pack" },
        { "spawn_bread", "Spawn Bread" },
        { "spawn_milk", "Spawn Milk" },
        { "event-hype-train", "Hype Effect" },
        { "send_comic_1", "Send Comic Set 1" },
        { "send_comic_2", "Send Comic Set 2" },
        { "send_comic_3", "Send Comic Set 3" },
        { "send_comic_4", "Send Comic Set 4" },
        { "send_comic_5", "Send Comic Set 5" },
        { "send_comic_6", "Send Comic Set 6" },
        { "send_comic_7", "Send Comic Set 7" },
        { "send_comic_8", "Send Comic Set 8" },
        { "send_comic_9", "Send Comic Set 9" },
        { "send_comic_10", "Send Comic Set 10" },
        { "send_comic_11", "Send Comic Set 11" },
        { "send_comic_12", "Send Comic Set 12" },
        { "send_comic_13", "Send Comic Set 13" },
        { "send_comic_14", "Send Comic Set 14" },
    };

    /// <summary>The display name for an effect code.</summary>
    /// <remarks>
    /// The fallback handles both naming styles effect codes come in: "speedUp" becomes "Speed Up",
    /// "stat_up_speed" becomes "Stat Up Speed".
    /// </remarks>
    public static string Pretty(string code)
    {
        if (string.IsNullOrWhiteSpace(code)) return "Effect";
        if (Names.TryGetValue(code, out string name)) return name;

        StringBuilder sb = new(code.Length + 4);
        bool startOfWord = true;
        foreach (char c in code)
        {
            if (c is '_' or '-')
            {
                sb.Append(' ');
                startOfWord = true;
                continue;
            }

            if (!startOfWord && char.IsUpper(c)) sb.Append(' ');

            sb.Append(startOfWord ? char.ToUpperInvariant(c) : c);
            startOfWord = false;
        }

        return sb.ToString();
    }
}
